# Generated by Django 5.1.5 on 2025-06-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lobby", "0004_alter_user_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lobby.user",
                    ),
                ),
                ("profession", models.CharField(max_length=40)),
                ("age", models.IntegerField()),
                ("hobby", models.CharField(max_length=40)),
                ("item", models.CharField(max_length=40)),
                ("fact", models.CharField(max_length=100)),
                ("health", models.CharField(max_length=100)),
            ],
        ),
    ]
