# Generated by Django 5.1.5 on 2025-06-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="fact_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="health_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="hobby_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="item_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="profession_is_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="proff_is_open",
            field=models.BooleanField(default=False),
        ),
    ]
