# Generated by Django 5.1.5 on 2025-07-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_rename_proff_is_open_userinfo_age_is_open"),
        ("lobby", "0011_session_lap_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voiting",
            fields=[
                (
                    "vote_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lobby.user",
                    ),
                ),
                ("count_of_voice", models.IntegerField()),
                ("have_voted", models.BooleanField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lobby.session"
                    ),
                ),
            ],
        ),
    ]
