# Generated by Django 5.1.5 on 2025-06-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0002_user_isowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
