# Generated by Django 5.1.5 on 2025-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0004_alter_user_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_user",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="line_of_user",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
