# Generated by Django 5.1.5 on 2025-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0005_session_current_user_session_line_of_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="current_user",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="session",
            name="line_of_user",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
