# Generated by Django 5.1.5 on 2025-06-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0006_alter_session_current_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="current_user",
            field=models.IntegerField(default=-1),
        ),
    ]
