# Generated by Django 5.1.5 on 2025-06-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0007_alter_session_current_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="current_user",
        ),
    ]
