# Generated by Django 5.1.5 on 2025-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0008_remove_session_current_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_user",
            field=models.IntegerField(default=-1),
        ),
    ]
