# Generated by Django 5.1.5 on 2025-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0009_session_current_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="state",
            field=models.CharField(default="wating", max_length=100),
        ),
    ]
