# Generated by Django 5.1.5 on 2025-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0010_alter_session_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="lap_state",
            field=models.CharField(default="player_move", max_length=100),
        ),
    ]
