# Generated by Django 5.1.5 on 2025-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0011_session_lap_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isAlive",
            field=models.BooleanField(default=True),
        ),
    ]
