# Generated by Django 5.1.5 on 2025-07-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0012_user_isalive"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="situation",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
