# Generated by Django 5.1.5 on 2025-07-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0013_session_situation"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="current_situation",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
